### ISSUE TITLE
I-de does not download the daily history of the counter

### ISSUE THREAD

**Issue by JimmyJimbolo** [ldotlopez/ha-ideenergy#38]
Hello.

I have been observing for several days that the historical data of the counter is not recovered, that is, the daily hourly graph that is obtained the next day.

I have this error in the log:

Este error se originó a partir de una integración personalizada.

Logger: homeassistant
Source: custom_components/ideenergy/historical_sensor.py:190
Integration: i-DE Energy Monitor (documentation, issues)
First occurred: 09:56:08 (126 occurrences)
Last logged: 19:28:46

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ideenergy/historical_sensor.py", line 190, in _save_states_into_recorder
    cutoff = latest_db_state.last_updated.replace(tzinfo=timezone.utc)
AttributeError: 'NoneType' object has no attribute 'replace'

Does it happen to anyone else?

**Comment by ldotlopez** [comment]
Current version is not compatible with current home assistant.

If you are running latest HA (>=2023.2.0) you have to use the git version of the integration. I have using it myself for a few days now and it's working fine. I want to publish a release tomorrow :crossed_fingers:

**Comment by JimmyJimbolo** [comment]
Ok. Muchas gracias Luis.

No se aun si probar eso de la version git o esperar...

**Comment by ldotlopez** [comment]
Ayer publiqué la versión para >= 2023.2.0 (requisito mínimo también).

**Comment by JimmyJimbolo** [comment]
Voy ahora a actualizar el core a la 2023.2.3 y luego lo hago con la tuya. ;-)

Supongo que me saldrá el aviso de la actualizacion automaticamente como siempre, ¿no?

Lo digo porque no he encontrado aun la forma de hacerlo con git. Ando verde en algunas cosas...

**Comment by JimmyJimbolo** [comment]
Ok.

Muchas gracias.

👍🏻

**Comment by JimmyJimbolo** [comment]
Hola. No me sale la actualizacion de la integracion. Porque no creo que se haya actualizado sola.

Una pregunta muy tonta, ¿como se la version que tengo instalada?

**Comment by ldotlopez** [comment]
Pues depende del método de instalación, si es HACS pueden entrar en la "tienda" -> integraciones -> ide energy y *creo* que la versión que aparece arriba a la izquierda es la instalada. 

![imagen](https://user-images.githubusercontent.com/99769/218040803-43f75ec1-bb0e-4724-932b-b2f1c75b4d9e.png)

Otra opción es buscar los ficheros de la integración: `custom_components/ideenergy/manifest.json` y revisar el campo `version`.

La versión compatible con 2023.2.3 es la 1.0.3.

**Comment by JimmyJimbolo** [comment]
Hola.

Tenia la 1.0.2. Y si no estoy equivocado, me ha salido el aviso de actualizacion justo despues de entrar en HACS.

Muchas gracias por la ayuda.
