### ISSUE TITLE
No hay forma que cargue, antes funcionaba perfectamente

### ISSUE THREAD

**Issue by janfajessen** [ldotlopez/ha-ideenergy#44]
Pensaba que se trataba por la nueva actualización de HA pero no. Esto es lo que pone en los logs de error:

Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/ideenergy/__init__.py:67
Integration: i-DE Energy Monitor (documentation, issues)
First occurred: 11:31:35 (2 occurrences)
Last logged: 11:32:35

Error setting up entry Iberdrola Distribución España - meter reading for ideenergy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ideenergy/__init__.py", line 67, in async_setup_entry
    contract_details = await api.get_contract_details()
  File "/usr/local/lib/python3.10/site-packages/ideenergy/client.py", line 65, in _wrap
    await client.login()
  File "/usr/local/lib/python3.10/site-packages/ideenergy/client.py", line 188, in login
    data = await self.request_json("POST", _LOGIN_ENDPOINT, json=payload)
  File "/usr/local/lib/python3.10/site-packages/ideenergy/client.py", line 144, in request_json
    buff = await self.request_bytes(method, url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ideenergy/client.py", line 149, in request_bytes
    resp = await self._request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ideenergy/client.py", line 158, in _request
    resp = await self._sess.request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

Espero que se pueda solucionar, muchas gracias de antemano por tu fantástico trabajo

**Comment by janfajessen** [comment]
Parece que no se puede acceder desde el extranjero..no sé si usando una VPN instalada en Home Assistant pero no sabría cómo hacerlo. Cierro incidencia
