### ISSUE TITLE
Cierre de cuenta debido a uso masivo.

### ISSUE THREAD

**Issue by marcoaperez** [ldotlopez/ha-ideenergy#77]
Hola, me han cerrado el acceso a i-DE por que uso de descargas masivas por la API. 

He tardado 1 mes en recuperar el acceso y ahora me da miedo volver a activar la integración.

Hay alguna manera de limitar la descarga de información?

**Comment by JimmyJimbolo** [comment]
Me pasa igual. Yo he vuelto a activar las lecturas de 2 contadores. A ver cuánto dura.

**Comment by Greali** [comment]
Me ha pasado 3 o 4 veces que he tenido que pedir que me desbloqueen la cuenta.
No creo que sea usable a día de hoy, creo que hay que revisar bien esto para que se limite a 1 petición al día o algo así.
Ya no me arriesgo a que me bloqueen la cuenta... ya que desde IDE dicen que exponen ningún tipo de API usable.

**Comment by ldotlopez** [comment]
@Greali la limitación está [integrada](https://github.com/ldotlopez/ha-ideenergy/blob/main/custom_components/ideenergy/coordinator.py#L36-L65) desde el primer día, que pueda existir un fallo puntual en la limitación es otra cosa.

Pero yo mismo uso la integración y, de haber algún problema, me suelo topar con él antes.

Dicho esto:
- ¿Qué versión de la integración estás usando? La versión actual es básicamente una reescritura sobre la que habla esta issue.
- ¿Qué configuración y sensores tienes activados?
- ¿Tienes activados varios contratos?
- Supongo que es difícil, pero ¿tienes los logs de cuando ha ocurrido esto?

Saludos.

**Comment by Greali** [comment]
@ldotlopez La verdad es que tengo un mix raro porque tuve que editar la extensión porque no me obtenía los consumos, aparentemente porque intentaba sacar temas de energía solar y yo no tengo nada de eso.
La última versión que subiste tampoco me funcionaba, la verdad no probé mucho más porque me estaban cancelando la cuenta a los minutos de hacer algunas llamadas... y luego tardan 3 o 4 días en desbloquear..

<img width="261" height="88" alt="Image" src="https://github.com/user-attachments/assets/e15b54cc-4188-48cc-b3bb-f0261cd4fdc4" />

No sé si esos 30 segundos tiene algo que ver o esto:

if False and self.state_timestamp_is_too_recent(
            last_success_state_key,
            last_success_max_age,
        ):

Que está a False.

**Comment by ldotlopez** [comment]
@Greali

¿En qué fichero y línea aparece ese `if False ...`? No lo encuentro en el código actual, así que puede que sea de una versión modificada.

Las versiones 1.x, 2.x y cualquier fork personalizado ya no tienen soporte activo, así que para poder ayudarte bien lo ideal sería partir de la **3.0.0a2**. Si al activarla tienes algún problema, abrimos un issue nuevo.

Una cosa que no está bien documentada todavía: para activar la integración por primera vez es necesario haber hecho login en la web dentro de los **15 minutos previos** (es una limitación del 2FA).

Para investigar el problema de los bloqueos necesito un poco más de contexto:
- Versión exacta
- Configuración y sensores que tienes activados
- ¿Tienes más de un contrato?
- Logs del momento en que ocurrió (si los tienes disponibles)

**Comment by Greali** [comment]
@ldotlopez Estoy usando ahora la última versión que publicaste pero me pasa lo que me pasaba en su día que en el consumo histórico no sale nada de los días pasados, ¿es el comportamiento normal?

Me salen en Unknown y no puedo añadir el consumo acumulado al panel de energía, entonces no me sirve.

He hecho login en la web con 2FA.

Me salen 2 mensajes de error en los logs, measure request failed es uno y el otro esto:

error updating dataset 'DIRECT_READING'
Traceback (most recent call last):
  File "/config/custom_components/ideenergy/coordinator.py", line 174, in _async_update_data
    updated_data[ds] = await fn()
                       ^^^^^^^^^^
  File "/config/custom_components/ideenergy/coordinator.py", line 209, in _async_get_direct_reading_data
    data = await self._client.get_measure()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/ideenergy/client.py", line 84, in _wrap
    return await fn(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/ideenergy/client.py", line 342, in get_measure
    raise CommandError(data)
ideenergy.client.CommandError: Command not succesful: {}
